[webservers]
172.31.18.92 ansible_ssh_user='ec2-user'

[todo_webservers]
172.31.62.128 ansible_ssh_user='ec2-user'

[db]
172.31.81.131 ansible_ssh_user='ubuntu' 
172.31.30.36 ansible_ssh_user='ubuntu' 

[lb]
172.31.85.187 ansible_ssh_user='ubuntu'