pipeline {
    agent any

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
      string(name: 'skip_tags', defaultValue: 'tooling',  description: 'This is the list of apps to skip')
    }

    stages {
      stage('Initial cleanup') {
        steps {
            dir("${WORKSPACE}") {
                deleteDir()
            }
        }
      }

      stage('Checkout SCM') {
        steps {
            git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/ahmedb24/ansible-project'
        }
      }

      stage('Build') {
        steps {
          script {
            sh 'echo "Building Stage"'
          }
        }
      }

      stage('Test') {
        steps {
          script {
            sh 'echo "Testing Stage"'
          }
        }
      }

      stage('Prepare Ansible For Execution') {
        steps {
          sh 'echo ${WORKSPACE}' 
          sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
        }
        environment {
            ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
        }
      }
      
      stage('Run ansible playbook') {
        steps {
            sh 'echo ${ANSIBLE_CONFIG}' 
            ansiblePlaybook credentialsId: 'private-key', 
            disableHostKeyChecking: true, 
            installation: 'ansible', 
            inventory: 'inventory/${inventory}.yml', 
            playbook: 'playbooks/site.yml',
            skippedTags: '${skip_tags}'
        }
      }
    }
}