pipeline {
    agent any

    stages {
    //   stage('Initial cleanup') {
    //     steps {
    //         dir("${WORKSPACE}") {
    //             deleteDir()
    //         }
    //     }
    //   }

      stage('Checkout SCM') {
        steps {
            git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/ahmedb24/ansible-project'
        }
      }

      stage('Build') {
        steps {
          script {
            sh 'echo "Building Stage"'
          }
        }
      }

      stage('Test') {
        steps {
          script {
            sh 'echo "Testing Stage"'
          }
        }
      }

      stage('Run ansible playbook') {
        steps {
            ansiblePlaybook credentialsId: 'universe', 
            disableHostKeyChecking: true, 
            installation: 'ansible', 
            inventory: 'inventory/dev.yml', 
            playbook: 'playbooks/site.yml'
        }
      }
    }

    post {
        // Clean after build
        always {
            cleanWs cleanWhenNotBuilt: true,
                    deleteDirs: true,
                    disableDeferredWipeout: false,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'INCLUDE']]
        }
    }
}