---
- name: install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

# SETUP TOOLING APP.
- include_tasks: "setup-tooling.yml"
  tags: tooling

# SETUP TODO APP.
- include_tasks: "setup-todo.yml"
  tags: todo
