---
- name:  initial cleanup, remove /var/www/html/ directory if present
  become: true
  ansible.builtin.file:
    path: /var/www/html/
    state: absent

- name: install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

# SETUP TOOLING APP.
- include_tasks: "setup-tooling.yml"
  tags: tooling

# SETUP TODO APP.
- include_tasks: "setup-todo.yml"
  tags: todo
