- name: install php7.4
  become: true
  shell: |
    rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    yum install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm
    yum module list php
    yum module enable php:remi-7.4 -y
    yum install -y php

- name: install php-mysql
  become: true
  yum:
    name: "php-mysql"
    state: present
