---
- name: Include dynamic variables
  # import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml

# - name: Database assignment
#   import_playbook: ../static-assignments/database.yml
#   when: db_is_required 

# - name: Webserver assignment
#   import_playbook: ../static-assignments/dev-webservers.yml

# - name: Loadbalancers assignment  
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required 